apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
subjects:
  - kind: ServiceAccount
    name: not-found-account
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
